name: movie_task
description: "A new Flutter project(task for new opportunity)."
publish_to: 'none' # Remove this line if you wish t
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  http: ^1.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  flutter_svg: ^1.0.0
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.1
  injectable: ^2.1.0 # Version 2
  json_annotation: ^4.7.0
  readmore: ^2.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  injectable_generator: ^2.1.3 # Version 2
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
